apiVersion: v1
kind: ConfigMap
metadata:
  name: boundary-config
  labels:
    {{- include "boundary-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  creationTimestamp: null
data:
  boundary-config-admin.hcl: |
    disable_mlock = true
    log_format    = "standard"
    controller {
      name        = "kubernetes-controller"
      description = "Boundary controller"
      database {
      {{- if .Values.vault.enabled }}
        url = "file:///vault/secrets/database-creds-admin.txt"
      {{- else }}
        url = "postgresql://{{.Values.database.username}}:{{.Values.database.password}}@{{ .Values.database.url }}:{{ .Values.database.port}}/{{.Values.database.dbName}}{{- if ne .Values.database.ssl true }}?sslmode=disable{{- end }}"
      {{- end }}
      }
      public_cluster_addr = "localhost"
    }
    worker {
      name        = "kubernetes-worker"
      description = "Boundary worker"
      address     = "localhost"
      controllers = ["localhost"]
      public_addr = "{{ .Values.publicAddress }}:{{ .Values.publicPort }}"
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "api"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "cluster"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "proxy"
      tls_disable = true
    }
    {{- if .Values.vault.enabled }}
    {{- $fqdn := .Values.vault.fqdn }}
    {{- $mountPath := .Values.vault.mountPath }}
    {{- $tlsSkip := .Values.vault.tlsSkipVerify }}
    {{- range $i, $purpose := list "root" "recovery" "worker-auth" }}
    kms "transit" {
      purpose         = "{{ $purpose }}"
      address         = "{{ $fqdn }}"
      disable_renewal = false

      key_name   = "{{ $purpose }}"
      mount_path = "{{ $mountPath }}"
      {{- if $tlsSkip }}
      tls_skip_verify = true
      {{- end }}
    }
    {{- end }}
    {{- else }}
    {{- range $purpose, $key := .Values.aead.keys }}
    kms "aead" {
      purpose = "{{ $purpose }}"
      key_id = "global_{{ $purpose }}"
      aead_type = "aes-gcm"
      key = "{{ $key }}"
    }
    {{- end }}
    {{- end }}
  boundary-config.hcl: |
    disable_mlock = true
    log_format    = "standard"
    controller {
      name        = "kubernetes-controller"
      description = "Boundary controller"
      database {
      {{- if .Values.vault.enabled }}
        url = "file:///vault/secrets/database-creds.txt"
      {{- else }}
        url = "postgresql://{{.Values.database.username}}:{{.Values.database.password}}@{{ .Values.database.url }}:{{ .Values.database.port}}/{{.Values.database.dbName}}{{- if ne .Values.database.ssl true }}?sslmode=disable{{- end }}"
      {{- end }}
      }
      public_cluster_addr = "localhost"
    }
    worker {
      name        = "kubernetes-worker"
      description = "Boundary worker"
      address     = "localhost"
      controllers = ["localhost"]
      public_addr = "{{ .Values.publicAddress }}:{{ .Values.publicPort }}"
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "api"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "cluster"
      tls_disable = true
    }
    listener "tcp" {
      address     = "0.0.0.0"
      purpose     = "proxy"
      tls_disable = true
    }
    {{- if .Values.vault.enabled }}
    {{- $fqdn := .Values.vault.fqdn }}
    {{- $mountPath := .Values.vault.mountPath }}
    {{- $tlsSkip := .Values.vault.tlsSkipVerify }}
    {{- range $i, $purpose := list "root" "recovery" "worker-auth" }}
    kms "transit" {
      purpose         = "{{ $purpose }}"
      address         = "{{ $fqdn }}"
      disable_renewal = false

      key_name   = "{{ $purpose }}"
      mount_path = "{{ $mountPath }}"
      {{- if $tlsSkip }}
      tls_skip_verify = true
      {{- end }}
    }
    {{- end }}
    {{- else }}
    {{- range $purpose, $key := .Values.aead.keys }}
    kms "aead" {
      purpose = "{{ $purpose }}"
      key_id = "global_{{ $purpose }}"
      aead_type = "aes-gcm"
      key = "{{ $key }}"
    }
    {{- end }}
    {{- end }}
