{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "boundary-chart.serviceAccountName" . }}
  labels:
    {{- include "boundary-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault-boundary
  namespace: default
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.22.0
  annotations:
    meta.helm.sh/release-name: vault
    meta.helm.sh/release-namespace: default
secrets:
  - name: vault-token
  - name: vault-boundary-token
  - name: vault-token-ql4hz

